framework:
    session:
        enabled: true
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native 